version: "2"

linters:
    default: "none"  # similar to disable-all: true in v1

    enable:
      - asasalint
      - asciicheck
      - bidichk
      - bodyclose
      - canonicalheader
#     - containedctx
      - contextcheck
      - copyloopvar
      - decorder
      - depguard
      - dogsled
      - dupword
      - errname
      - errorlint
      - fatcontext
      - ginkgolinter
      - gocheckcompilerdirectives
      - gochecknoinits
      - gochecksumtype
      - goconst
      - gocyclo
      - godot
      - goheader
      - gomoddirectives
      - goprintffuncname
      - grouper
      - importas
      - inamedparam
      - ineffassign
      - intrange
      - loggercheck
      - maintidx
      - makezero
      - mirror
      - misspell
      - nakedret
      - nilerr
      - nlreturn
      - nolintlint
      - nosprintfhostport
      - paralleltest
      - predeclared
      - promlinter
      - protogetter
      - reassign
      - rowserrcheck
      - sloglint
      - spancheck
      - sqlclosecheck
      - testableexamples
      - testifylint
      - testpackage
      - thelper
      - tparallel
      - unconvert
      - unparam
      - unused
      - whitespace
      - zerologlint

    settings:
      errcheck:
        check-type-assertions: true

      goconst:
        min-len: 2
        min-occurrences: 3

      gocritic:
        enabled-tags:
          - diagnostic
          - experimental
          - opinionated
          - performance
          - style

      govet:
        enable:
          - fieldalignment

      nolintlint:
        require-explanation: true
        require-specific: true

      depguard:
        rules:
          main:
            list-mode: lax
            files:
              - "!**/*_a _file.go"
            allow:
              - $gostd
              - github.com/OpenPeeDeeP
            deny:
              - pkg: "github.com/sirupsen/logrus"
                desc: not allowed
              - pkg: "github.com/pkg/errors"
                desc: Should be replaced by standard lib errors package

formatters:
    enable:
      - gofmt
      - goimports

output:
    format:
      colored-line-number:
        print-issued-lines: true
        print-linter-name: true
    uniq-by-line: false
    path-prefix: ""
    sort-results: true
    sort-order:
      - linter
      - severity
      - file
    show-stats: true

run:
    concurrency: 4
    timeout: 5m
    issues-exit-code: 1
    allow-parallel-runners: true
    allow-serial-runners: true
    go: "1.25"