version: "2"

run:
  go: "1.25"
  timeout: 5m
  allow-parallel-runners: true

linters:
  default: none
  enable:
    # Bugs & correctness
    - errcheck        # Check for unchecked errors
#    - govet           # Suspicious constructs (go vet)
    - ineffassign     # Detect ineffectual assignments
#    - staticcheck     # Static analysis checks
    - unused          # Unused code

    # Style & best practices
#    - revive          # Replacement for golint
    - misspell        # Spelling mistakes in comments/strings
    - whitespace      # Unnecessary blank lines

    # Complexity & maintainability
    - cyclop          # Cyclomatic complexity
    - gocognit        # Cognitive complexity
    - funlen          # Function length
    - maintidx        # Maintainability index

    # Security
    - gosec           # Security issues

    # Performance
    - prealloc        # Slice preallocation suggestions
    - bodyclose       # HTTP response body closure

    # Error handling
#    - wrapcheck       # Errors wrapped before returning
    - errorlint       # Error wrapping issues

    # Code cleanliness
#    - godot           # Comments end in a period
    - nolintlint      # Malformed nolint directives
    - unconvert       # Unnecessary type conversions
    - unparam         # Unused function parameters
    - dupl            # Code duplication
#    - gocritic        # Various code checks

linters-settings:
  cyclop:
    max-complexity: 15

  gocognit:
    min-complexity: 20

  funlen:
    lines: 80
    statements: 50

  gosec:
    excludes:
      - G104  # Unhandled errors in defer (handled by errcheck)

  revive:
    rules:
      - name: exported
      - name: unused-parameter
      - name: var-naming

  gocritic:
    enabled-tags:
      - diagnostic
      - style
      - performance

  wrapcheck:
    ignoreSigs:
      - .Errorf(
      - errors.New(
      - errors.Unwrap(
      - .Wrap(
      - .Wrapf(

  dupl:
    threshold: 150

  misspell:
    locale: US

issues:
  max-same-issues: 5
  max-issues-per-linter: 50

  exclude-rules:
    # Relax some rules in test files
    - path: _test\.go
      linters:
        - funlen
        - dupl
        - gosec
        - wrapcheck
        - gocognit

    # Relax complexity in main entrypoints
    - path: cmd/
      linters:
        - cyclop
        - funlen

  fix: false